@rootURL = http://localhost:5191

###
GET {{rootURL}}/weatherforecast
Accept: application/json

###
GET {{rootURL}}/api/books
Accept: application/json

###
GET {{rootURL}}/api/books/1
Accept: application/json

###
POST {{rootURL}}/api/books
Content-Type: application/json

{
    "title": "Book of Books",
    "author": "Draks",
    "yearPublished": 2025
}

###
PUT {{rootURL}}/api/books/4
Content-Type: application/json

{
    "id": 4,
    "title": "1984 - Zaktualizowany",
    "author": "Me",
    "yearPublished": 1949
}

###
DELETE {{rootURL}}/api/books/4